#pragma once

#include "../SDK.h"

// Name: Freddys, Version: 4.2.1

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.ChangeStateToIdle
struct UFunWithPlushtrap_ABP_C_ChangeStateToIdle_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.ResetTimer
struct UFunWithPlushtrap_ABP_C_ResetTimer_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.ChangeStateToMove
struct UFunWithPlushtrap_ABP_C_ChangeStateToMove_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.Fun With Plush Trap BP Ref
struct UFunWithPlushtrap_ABP_C_Fun_With_Plush_Trap_BP_Ref_Params
{
	class AFun_With_PlushTrap_BP_C*                    Fun_with_PlushTrap_BP_Ref;                                // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.ProcessMoveState
struct UFunWithPlushtrap_ABP_C_ProcessMoveState_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_234A97D74AB05A40EAC072AD67609BBC
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_234A97D74AB05A40EAC072AD67609BBC_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_7C028E8B4C4253FE2E9F0AB3FDE0BA47
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_7C028E8B4C4253FE2E9F0AB3FDE0BA47_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_733358AA4E1D6249C4A0AFA85D790B25
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_733358AA4E1D6249C4A0AFA85D790B25_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_8EEB36A34B6C640C653FBB8BBD7A257C
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_8EEB36A34B6C640C653FBB8BBD7A257C_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_B806FB604F7954601A1FF08BE623580D
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_B806FB604F7954601A1FF08BE623580D_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_DF4CAD724108B1DCD751949C6CC3CFCE
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_DF4CAD724108B1DCD751949C6CC3CFCE_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_30F02C8D4C30EFDB389EDBBD6CCBE37C
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_30F02C8D4C30EFDB389EDBBD6CCBE37C_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_2447944C4A346572E5AF39AB95D84225
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_2447944C4A346572E5AF39AB95D84225_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_CE4532564D86C320EC797A9559CAB907
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_CE4532564D86C320EC797A9559CAB907_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_E4B257CB4C1DE097EB24ABBF6D01A95A
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_E4B257CB4C1DE097EB24ABBF6D01A95A_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_551F224C451806F9327452B59ABD7C2E
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_551F224C451806F9327452B59ABD7C2E_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_311D77664B55044C434320A24DAF2D20
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_311D77664B55044C434320A24DAF2D20_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1B5E1EAC4AD6124BB131108468BC4105
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1B5E1EAC4AD6124BB131108468BC4105_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_73331FCC4739130EE41E72938D84CE30
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_73331FCC4739130EE41E72938D84CE30_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_5418351F4B017D28EEE9ABBA13745F67
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_5418351F4B017D28EEE9ABBA13745F67_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_9596E6B44BE5EC9AB96A3A9B0219E848
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_9596E6B44BE5EC9AB96A3A9B0219E848_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1E4530BD4E556114E978649AF961221D
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1E4530BD4E556114E978649AF961221D_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_639D3CEC44BC66C07B6A68B81D402A07
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_639D3CEC44BC66C07B6A68B81D402A07_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_D894E72C48E3C7A8546240A18CFB71BF
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_D894E72C48E3C7A8546240A18CFB71BF_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1E6A24504107F8ACF300B58AA75D68CD
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1E6A24504107F8ACF300B58AA75D68CD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_Chair
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_Chair_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_Back
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_Back_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Idle_BLD
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Idle_BLD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Idle_BRD
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Idle_BRD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1B2A82734A47CFA28E3979B28DB04DE2
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_1B2A82734A47CFA28E3979B28DB04DE2_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Idle_Mid
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Idle_Mid_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Invis_2
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Invis_2_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Invis_3
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Invis_3_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Idle_FRD
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Idle_FRD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PT_Idle_FLD
struct UFunWithPlushtrap_ABP_C_AnimNotify_PT_Idle_FLD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_A67C7B93481A5A9EAF8E6AB8DAFB9C89
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_A67C7B93481A5A9EAF8E6AB8DAFB9C89_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_F004EA224AB424732BCA8EB24132E65B
struct UFunWithPlushtrap_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FunWithPlushtrap_ABP_AnimGraphNode_TransitionResult_F004EA224AB424732BCA8EB24132E65B_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_PlayerKilled
struct UFunWithPlushtrap_ABP_C_AnimNotify_PlayerKilled_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Invis
struct UFunWithPlushtrap_ABP_C_AnimNotify_Invis_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_BLD
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_BLD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_BRD
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_BRD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_Mid
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_Mid_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Invis2
struct UFunWithPlushtrap_ABP_C_AnimNotify_Invis2_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_FLD
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_FLD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_FRD
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_FRD_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.AnimNotify_Idle_OnX
struct UFunWithPlushtrap_ABP_C_AnimNotify_Idle_OnX_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.OnPlushTrapStateChanged
struct UFunWithPlushtrap_ABP_C_OnPlushTrapStateChanged_Params
{
	class UPlushTrapState_C*                           PlushTrapState;                                           // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.StartIdleTimer
struct UFunWithPlushtrap_ABP_C_StartIdleTimer_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.Initialize
struct UFunWithPlushtrap_ABP_C_Initialize_Params
{
};

// Function FunWithPlushtrap_ABP.FunWithPlushtrap_ABP_C.ExecuteUbergraph_FunWithPlushtrap_ABP
struct UFunWithPlushtrap_ABP_C_ExecuteUbergraph_FunWithPlushtrap_ABP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
