#pragma once

#include "../SDK.h"

// Name: Freddys, Version: 4.2.1

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ResetTimer
struct UFun_With_PlushTrap_Anim_BP_C_ResetTimer_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ChangeStateToIdle
struct UFun_With_PlushTrap_Anim_BP_C_ChangeStateToIdle_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.Fun With Plush Trap BP Ref
struct UFun_With_PlushTrap_Anim_BP_C_Fun_With_Plush_Trap_BP_Ref_Params
{
	class AFun_With_PlushTrap_BP_C*                    Fun_with_PlushTrap_BP_Ref;                                // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ChangeStateToMove
struct UFun_With_PlushTrap_Anim_BP_C_ChangeStateToMove_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ProcessIdleState
struct UFun_With_PlushTrap_Anim_BP_C_ProcessIdleState_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ProcessKillState
struct UFun_With_PlushTrap_Anim_BP_C_ProcessKillState_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ProcessMoveState
struct UFun_With_PlushTrap_Anim_BP_C_ProcessMoveState_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ChooseNextAnimation
struct UFun_With_PlushTrap_Anim_BP_C_ChooseNextAnimation_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ChangeAnimationState
struct UFun_With_PlushTrap_Anim_BP_C_ChangeAnimationState_Params
{
	unsigned char                                      AnimState;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_6F9FCC964C90CAE6FB4D2283C401F29E
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_6F9FCC964C90CAE6FB4D2283C401F29E_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_357872A64228B70F0C77228EB5BFBA82
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_357872A64228B70F0C77228EB5BFBA82_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_E17005F449D3586312E80C8FBA3DF937
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_E17005F449D3586312E80C8FBA3DF937_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_ED65CFB541C5445458102DA35E13575A
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_ED65CFB541C5445458102DA35E13575A_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_698FDDE64ECE8106BB365B8A6671C00D
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_698FDDE64ECE8106BB365B8A6671C00D_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_F031FB3B4A2871BE00D8B5A201969B19
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_F031FB3B4A2871BE00D8B5A201969B19_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_7D6783CC4D5D297832BC8E975A8CA829
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_7D6783CC4D5D297832BC8E975A8CA829_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_9C7D3D2B4FF96CDFE7EFD3BC314D99E5
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_9C7D3D2B4FF96CDFE7EFD3BC314D99E5_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_77608687413C878CC180E8920A223E11
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_77608687413C878CC180E8920A223E11_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2C419E514185366E22C03D9065C65F02
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2C419E514185366E22C03D9065C65F02_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_9791BF5240A055AE6803198C05BAEC34
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_9791BF5240A055AE6803198C05BAEC34_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_C209460F400AB186B4960BAB69A90788
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_C209460F400AB186B4960BAB69A90788_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_F22C114E41FECC22FB94E8BF7C274E11
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_F22C114E41FECC22FB94E8BF7C274E11_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_0DA80C2448EDC910962757960685D977
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_0DA80C2448EDC910962757960685D977_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_02989EA845F3412E5DB6758FC2C5ED12
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_02989EA845F3412E5DB6758FC2C5ED12_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_534D540D489E506F51E249BF42582BDC
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_534D540D489E506F51E249BF42582BDC_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_1DEFF24F49520C0A8C38469F40F6CB7C
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_1DEFF24F49520C0A8C38469F40F6CB7C_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_B552F3DC4B4D9CA380E05F85AD481DCC
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_B552F3DC4B4D9CA380E05F85AD481DCC_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_Idle_Chair
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_Idle_Chair_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_Idle_Back
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_Idle_Back_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2C6C5EEE42675F066ECDAB8F27D08B78
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2C6C5EEE42675F066ECDAB8F27D08B78_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_6928CF91428C809D6751FAB33649CBD6
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_6928CF91428C809D6751FAB33649CBD6_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_BLD
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_BLD_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_BRD
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_BRD_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_Mid
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_Mid_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Invis_2
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Invis_2_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_1CCE0CE8417F73EF64D5FCA02021F8C8
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_1CCE0CE8417F73EF64D5FCA02021F8C8_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Invis_3
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Invis_3_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_FRD
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_FRD_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_FLD
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_FLD_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PT_Idle_X
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PT_Idle_X_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.AnimNotify_PlayerKilled
struct UFun_With_PlushTrap_Anim_BP_C_AnimNotify_PlayerKilled_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.BlueprintBeginPlay
struct UFun_With_PlushTrap_Anim_BP_C_BlueprintBeginPlay_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.OnPlushTrapStateChanged
struct UFun_With_PlushTrap_Anim_BP_C_OnPlushTrapStateChanged_Params
{
	class UPlushTrapState_C*                           PlushTrapState;                                           // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.StartIdleTimer
struct UFun_With_PlushTrap_Anim_BP_C_StartIdleTimer_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_7907F424440EDADB90EC71A9D0439840
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_7907F424440EDADB90EC71A9D0439840_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2182A2C24302B691AAB0198A59F6A9FB
struct UFun_With_PlushTrap_Anim_BP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_AnimGraphNode_TransitionResult_2182A2C24302B691AAB0198A59F6A9FB_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP
struct UFun_With_PlushTrap_Anim_BP_C_ExecuteUbergraph_Fun_With_PlushTrap_Anim_BP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.PlayerCanWin__DelegateSignature
struct UFun_With_PlushTrap_Anim_BP_C_PlayerCanWin__DelegateSignature_Params
{
};

// Function Fun_With_PlushTrap_Anim_BP.Fun_With_PlushTrap_Anim_BP_C.KillPlayer__DelegateSignature
struct UFun_With_PlushTrap_Anim_BP_C_KillPlayer__DelegateSignature_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
