#pragma once

#include "../SDK.h"

// Name: Freddys, Version: 4.2.1

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function NMFredbear_ABP.NMFredbear_ABP_C.ResetEyeEmissive
struct UNMFredbear_ABP_C_ResetEyeEmissive_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.ChangeStateToMove
struct UNMFredbear_ABP_C_ChangeStateToMove_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.ChooseNextAnimation
struct UNMFredbear_ABP_C_ChooseNextAnimation_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.ResetTimer
struct UNMFredbear_ABP_C_ResetTimer_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_8FABE2E3462597B5CF9DE5AEA1FF3F88
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_8FABE2E3462597B5CF9DE5AEA1FF3F88_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FD8D2F334928F0D6311FBCB6DDEC1A25
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FD8D2F334928F0D6311FBCB6DDEC1A25_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_B9491DD94E1F5AE061DCAA96EF23016D
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_B9491DD94E1F5AE061DCAA96EF23016D_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_2E4EF35D465C2C9047327681D51957D7
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_2E4EF35D465C2C9047327681D51957D7_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FBE726074DB586278B2EE09DF02F309A
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FBE726074DB586278B2EE09DF02F309A_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_D504D0F544BC2CA6DB655ABC0103F586
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_D504D0F544BC2CA6DB655ABC0103F586_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_118C985F42CBC596E899948C2EB8EE6B
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_118C985F42CBC596E899948C2EB8EE6B_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_EFBEE0344C9B45C7BD9BC7922E8B846C
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_EFBEE0344C9B45C7BD9BC7922E8B846C_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_BB71413145E30219078A9AB98F02D41A
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_BB71413145E30219078A9AB98F02D41A_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_505F54E24D3472D8829BC9B2F0AE4D98
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_505F54E24D3472D8829BC9B2F0AE4D98_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_ACCB7C5F4FF3F124F8A0539EC896FECB
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_ACCB7C5F4FF3F124F8A0539EC896FECB_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_C33EC15141B35EB98F2B8A9651CC1949
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_C33EC15141B35EB98F2B8A9651CC1949_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_0739796546F1FCA2BE007BB980068E27
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_0739796546F1FCA2BE007BB980068E27_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_58C6290147EFE8848B15F588793D384D
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_58C6290147EFE8848B15F588793D384D_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_F891B5AF497AFF96ECDD33863FE7C712
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_F891B5AF497AFF96ECDD33863FE7C712_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_0D75F910421A057796A5A2820DCFCA8A
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_0D75F910421A057796A5A2820DCFCA8A_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_4F9FE00B4D5499297CB2B08B7EF02E71
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_4F9FE00B4D5499297CB2B08B7EF02E71_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_839ACDDF4EF6274B0F0EFBAA8ADB595C
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_839ACDDF4EF6274B0F0EFBAA8ADB595C_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_A25539944E60F29F21EEBBA022BEE057
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_A25539944E60F29F21EEBBA022BEE057_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_D6BBD49E469B473827ADED93D8122737
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_D6BBD49E469B473827ADED93D8122737_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_10537D9B4F10C7284A7F89935B5F9EE7
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_10537D9B4F10C7284A7F89935B5F9EE7_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_57E4868849121DFA37D5EA90687D74D2
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_57E4868849121DFA37D5EA90687D74D2_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_923F59424C07978A0B8EE6B473B27247
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_923F59424C07978A0B8EE6B473B27247_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_3B08523B415694C7F3E95BA85BAFBA92
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_3B08523B415694C7F3E95BA85BAFBA92_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_46587F4C40413AD389233C9E2F0F08F9
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_46587F4C40413AD389233C9E2F0F08F9_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_D9F04513475778B4EEDF239B7B609B7A
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_D9F04513475778B4EEDF239B7B609B7A_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_AEE011CB4A597FDE8CFF36BA3AB39F1C
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_AEE011CB4A597FDE8CFF36BA3AB39F1C_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_843D4A9448B5F17501F4DDB7E9E24BD6
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_843D4A9448B5F17501F4DDB7E9E24BD6_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FAF006FE450EE21FD2CE5FB1240B63AE
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_FAF006FE450EE21FD2CE5FB1240B63AE_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_7D41913B4E7514DA4393FFAD65D57D0E
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_7D41913B4E7514DA4393FFAD65D57D0E_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_30674FDC43FBEFEF9E57C4839E56A8E0
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_30674FDC43FBEFEF9E57C4839E56A8E0_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_1234C14841651C4E9C8C1C8C0924B4B8
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_1234C14841651C4E9C8C1C8C0924B4B8_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_A41D5B1A4B97E62291A89A832F758BFC
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_A41D5B1A4B97E62291A89A832F758BFC_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_A88B9B0344A19C518F92DB90A4901C2A
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_A88B9B0344A19C518F92DB90A4901C2A_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_3F88C5A04587105AA49BEBA68AF15A30
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_3F88C5A04587105AA49BEBA68AF15A30_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_5EF57EEA4256E822DAAD99BD4081855E
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_5EF57EEA4256E822DAAD99BD4081855E_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_691D404E4ECF8FE8B67C749EADCDDA3E
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_691D404E4ECF8FE8B67C749EADCDDA3E_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_DBBE56DE44FF4DD0E774348CEEC851A2
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_SequencePlayer_DBBE56DE44FF4DD0E774348CEEC851A2_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_23B544DD48E1C62A787C7188BF024879
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_23B544DD48E1C62A787C7188BF024879_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.BlueprintUpdateAnimation
struct UNMFredbear_ABP_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.BlueprintBeginPlay
struct UNMFredbear_ABP_C_BlueprintBeginPlay_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_Notify_Jumpscare
struct UNMFredbear_ABP_C_AnimNotify_Notify_Jumpscare_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_Notify_FinishedAnimation
struct UNMFredbear_ABP_C_AnimNotify_Notify_FinishedAnimation_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_Notify_StopTimer
struct UNMFredbear_ABP_C_AnimNotify_Notify_StopTimer_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_Notify_FlashLightJumperScare
struct UNMFredbear_ABP_C_AnimNotify_Notify_FlashLightJumperScare_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_Notify_FredLaugh
struct UNMFredbear_ABP_C_AnimNotify_Notify_FredLaugh_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_DisableLightEmissive
struct UNMFredbear_ABP_C_AnimNotify_DisableLightEmissive_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_TurnEyesOn
struct UNMFredbear_ABP_C_AnimNotify_TurnEyesOn_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_AA349170415BA7141B7776AF2B175D5E
struct UNMFredbear_ABP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_NMFredbear_ABP_AnimGraphNode_TransitionResult_AA349170415BA7141B7776AF2B175D5E_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.ClearEyeEmissive
struct UNMFredbear_ABP_C_ClearEyeEmissive_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.AnimNotify_LightUpEyes
struct UNMFredbear_ABP_C_AnimNotify_LightUpEyes_Params
{
};

// Function NMFredbear_ABP.NMFredbear_ABP_C.ExecuteUbergraph_NMFredbear_ABP
struct UNMFredbear_ABP_C_ExecuteUbergraph_NMFredbear_ABP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
